language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "4"

before_install:
  - nvm install 6
  - nvm use 6
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH

before_script:
  - nvm use $TRAVIS_NODE_VERSION
env:
  global:
  - EMBER_ENV=production
